"""phone_numbers inbound_agent_id set null on agent delete

Revision ID: cbbb8ddee9b7
Revises: 6c1c3d4cf23a
Create Date: 2026-08-15 16:20:57.313853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbbb8ddee9b7'
down_revision: Union[str, Sequence[str], None] = '6c1c3d4cf23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('phone_numbers_inbound_agent_id_fkey'), 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'phone_numbers', 'agents', ['inbound_agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(op.f('phone_numbers_inbound_agent_id_fkey'), 'phone_numbers', 'agents', ['inbound_agent_id'], ['id'])
    # ### end Alembic commands ###
